In [1]:
## Data Collection
import nltk
nltk.download('gutenberg')
from nltk.corpus import gutenberg
import pandas as pd

[nltk_data] Downloading package gutenberg to
[nltk_data]     C:\Users\DEVANSH\AppData\Roaming\nltk_data...
[nltk_data]   Package gutenberg is already up-to-date!


In [2]:
## load the dataset
data = gutenberg.raw('shakespeare-hamlet.txt')

## save to a file
with open('hamlet.txt', 'w') as file:
    file.write(data)

In [3]:
## Data Preprocessing
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import pad_sequences
from sklearn.model_selection import train_test_split

## load the dataset 
with open('hamlet.txt', 'r') as file:
    text = file.readlines() ## give a list of text.

## creating the indexes for the text
tokenizer = Tokenizer()
tokenizer.fit_on_texts(text) # requires list of sentences.

total_words = len(tokenizer.word_index) + 1
total_words

4818

In [4]:
text

['[The Tragedie of Hamlet by William Shakespeare 1599]\n',
 '\n',
 '\n',
 'Actus Primus. Scoena Prima.\n',
 '\n',
 'Enter Barnardo and Francisco two Centinels.\n',
 '\n',
 "  Barnardo. Who's there?\n",
 '  Fran. Nay answer me: Stand & vnfold\n',
 'your selfe\n',
 '\n',
 '   Bar. Long liue the King\n',
 '\n',
 '   Fran. Barnardo?\n',
 '  Bar. He\n',
 '\n',
 '   Fran. You come most carefully vpon your houre\n',
 '\n',
 "   Bar. 'Tis now strook twelue, get thee to bed Francisco\n",
 '\n',
 "   Fran. For this releefe much thankes: 'Tis bitter cold,\n",
 'And I am sicke at heart\n',
 '\n',
 '   Barn. Haue you had quiet Guard?\n',
 '  Fran. Not a Mouse stirring\n',
 '\n',
 '   Barn. Well, goodnight. If you do meet Horatio and\n',
 'Marcellus, the Riuals of my Watch, bid them make hast.\n',
 'Enter Horatio and Marcellus.\n',
 '\n',
 "  Fran. I thinke I heare them. Stand: who's there?\n",
 '  Hor. Friends to this ground\n',
 '\n',
 '   Mar. And Leige-men to the Dane\n',
 '\n',
 '   Fran. Giue 

In [5]:
tokenizer.word_index

{'the': 1,
 'and': 2,
 'to': 3,
 'of': 4,
 'i': 5,
 'you': 6,
 'a': 7,
 'my': 8,
 'it': 9,
 'in': 10,
 'that': 11,
 'ham': 12,
 'is': 13,
 'not': 14,
 'his': 15,
 'this': 16,
 'with': 17,
 'your': 18,
 'but': 19,
 'for': 20,
 'me': 21,
 'lord': 22,
 'as': 23,
 'what': 24,
 'he': 25,
 'be': 26,
 'so': 27,
 'him': 28,
 'haue': 29,
 'king': 30,
 'will': 31,
 'no': 32,
 'our': 33,
 'we': 34,
 'on': 35,
 'are': 36,
 'if': 37,
 'all': 38,
 'then': 39,
 'shall': 40,
 'by': 41,
 'thou': 42,
 'come': 43,
 'or': 44,
 'hamlet': 45,
 'good': 46,
 'do': 47,
 'hor': 48,
 'her': 49,
 'let': 50,
 'now': 51,
 'thy': 52,
 'how': 53,
 'more': 54,
 'they': 55,
 'from': 56,
 'enter': 57,
 'at': 58,
 'was': 59,
 'oh': 60,
 'like': 61,
 'most': 62,
 'there': 63,
 'well': 64,
 'know': 65,
 'selfe': 66,
 'would': 67,
 'them': 68,
 'loue': 69,
 'may': 70,
 "'tis": 71,
 'vs': 72,
 'sir': 73,
 'qu': 74,
 'which': 75,
 'did': 76,
 'why': 77,
 'laer': 78,
 'giue': 79,
 'thee': 80,
 'ile': 81,
 'must': 82,
 'hath': 

- We have done this 'tokenizer.texts_to_sequences([line])[0]' because the text_to_sequences always returns a list of sequences because it expects a list of texts. so it gives list of list like this [[1, 687, 4, 45]] that's why [0]


- And since blank line or "/n" were giving [] in our sequence so to avoid we have used this if condition

In [6]:
## creating input sequences for the sentence
## coverting our text into sequences. I love AI => [2,6,7] like that
input_sequences = []
for line in text:
    
    token_list = tokenizer.texts_to_sequences([line])[0] ## it should be in list form 
    if len(token_list)==0:
        continue

    ## so whenever we are doing this next_word prediction model then we create n_gram sequence.
    ## It is standard approach because each n-gram give the model training example.
    for i in range(1, len(token_list)):
        n_grams_sequence = token_list[:i+1]
        input_sequences.append(n_grams_sequence)

input_sequences


[[1, 687],
 [1, 687, 4],
 [1, 687, 4, 45],
 [1, 687, 4, 45, 41],
 [1, 687, 4, 45, 41, 1886],
 [1, 687, 4, 45, 41, 1886, 1887],
 [1, 687, 4, 45, 41, 1886, 1887, 1888],
 [1180, 1889],
 [1180, 1889, 1890],
 [1180, 1889, 1890, 1891],
 [57, 407],
 [57, 407, 2],
 [57, 407, 2, 1181],
 [57, 407, 2, 1181, 177],
 [57, 407, 2, 1181, 177, 1892],
 [407, 1182],
 [407, 1182, 63],
 [408, 162],
 [408, 162, 377],
 [408, 162, 377, 21],
 [408, 162, 377, 21, 247],
 [408, 162, 377, 21, 247, 882],
 [18, 66],
 [451, 224],
 [451, 224, 248],
 [451, 224, 248, 1],
 [451, 224, 248, 1, 30],
 [408, 407],
 [451, 25],
 [408, 6],
 [408, 6, 43],
 [408, 6, 43, 62],
 [408, 6, 43, 62, 1893],
 [408, 6, 43, 62, 1893, 96],
 [408, 6, 43, 62, 1893, 96, 18],
 [408, 6, 43, 62, 1893, 96, 18, 566],
 [451, 71],
 [451, 71, 51],
 [451, 71, 51, 1894],
 [451, 71, 51, 1894, 567],
 [451, 71, 51, 1894, 567, 378],
 [451, 71, 51, 1894, 567, 378, 80],
 [451, 71, 51, 1894, 567, 378, 80, 3],
 [451, 71, 51, 1894, 567, 378, 80, 3, 273],
 [451, 71

In [7]:
## Pad_sequences
max_sequence_len = max([len(x) for x in input_sequences])
max_sequence_len

14

In [8]:
input_sequences = pad_sequences(input_sequences, maxlen=max_sequence_len, padding='pre')
input_sequences

array([[   0,    0,    0, ...,    0,    1,  687],
       [   0,    0,    0, ...,    1,  687,    4],
       [   0,    0,    0, ...,  687,    4,   45],
       ...,
       [   0,    0,    0, ...,    4,   45, 1047],
       [   0,    0,    0, ...,   45, 1047,    4],
       [   0,    0,    0, ..., 1047,    4,  193]])

In [9]:
## create predictors and labels
import tensorflow as tf
x,y=input_sequences[:, :-1], input_sequences[:, -1]
x

array([[   0,    0,    0, ...,    0,    0,    1],
       [   0,    0,    0, ...,    0,    1,  687],
       [   0,    0,    0, ...,    1,  687,    4],
       ...,
       [   0,    0,    0, ...,  687,    4,   45],
       [   0,    0,    0, ...,    4,   45, 1047],
       [   0,    0,    0, ...,   45, 1047,    4]])

In [10]:
y

array([ 687,    4,   45, ..., 1047,    4,  193])

In [11]:
## converting i/p label into categories using one hot encoding
y = tf.keras.utils.to_categorical(y, num_classes=total_words)
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [12]:
# Split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

- return_sequences is important for stacking when use multiple LSTM layer because it return the hidden state every time step which is expected by second LSTM as input

In [13]:
## Train our LSTM
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, LSTM, Dropout
from scikeras.wrappers import KerasClassifier
from sklearn.model_selection import GridSearchCV

loss = tf.keras.losses.CategoricalCrossentropy()

## Define the model

model = Sequential()
model.add(Embedding(total_words, output_dim=100, input_length=max_sequence_len - 1)) ## since our x_train is 13 length as we have removed last col for y_train
model.add(LSTM(150, return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(100)) ## other layer
model.add(Dense(total_words, activation="softmax"))
model.add(Dropout(0.3))
model.compile(optimizer="adam", loss = loss, metrics=["accuracy"])
  


In [14]:
from tensorflow.keras.callbacks import TensorBoard,EarlyStopping
log_dir = 'logs/fit'
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1, write_graph=True)

In [15]:
earlyStopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [16]:
## convert the keras_model to the scikit estimator
history = model.fit(x_train, y_train, verbose=1, epochs=200, batch_size=64, validation_split=0.2, callbacks=[tensorboard_callback])

Epoch 1/200


258/258 [==============================] - 17s 50ms/step - loss: 9.5927 - accuracy: 0.0298 - val_loss: 6.8703 - val_accuracy: 0.0352
Epoch 2/200
258/258 [==============================] - 9s 35ms/step - loss: 9.2397 - accuracy: 0.0311 - val_loss: 6.7983 - val_accuracy: 0.0352
Epoch 3/200
258/258 [==============================] - 8s 29ms/step - loss: 9.0817 - accuracy: 0.0310 - val_loss: 6.8659 - val_accuracy: 0.0352
Epoch 4/200
258/258 [==============================] - 7s 26ms/step - loss: 9.0184 - accuracy: 0.0356 - val_loss: 6.8740 - val_accuracy: 0.0415
Epoch 5/200
258/258 [==============================] - 7s 26ms/step - loss: 9.0100 - accuracy: 0.0368 - val_loss: 6.9002 - val_accuracy: 0.0474
Epoch 6/200
258/258 [==============================] - 7s 26ms/step - loss: 8.9697 - accuracy: 0.0418 - val_loss: 6.9065 - val_accuracy: 0.0525
Epoch 7/200
258/258 [==============================] - 7s 26ms/step - loss: 8.8657 - accuracy: 0.0454 - val_loss: 6.9143 - val_accura

- If the user enters more words than the model can accept, keep only the last (max_sequence_len - 1) words, because those are the most relevant for predicting the next word.

In [32]:
model.save("next_word_lstm.h5")

c:\Users\DEVANSH\Desktop\New folder\venv\lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [18]:
## function to predict the next word
def predict_next_word(model, tokenizer, text, max_sequence_len):
    token_list = tokenizer.texts_to_sequences([text])[0]

    ## this make sure if new sentence > max then it selects max_len_words from last 
    ## since to predict next_word context from last word play more role.
    if len(token_list) > max_sequence_len:
        token_list = token_list[-(max_sequence_len - 1):]

    token_list = pad_sequences([token_list], maxlen=max_sequence_len - 1, padding='pre')
    predicted = model.predict(token_list, verbose=0)

    predicted_word_index = np.argmax(predicted, axis=1)[0]
    for word, index in tokenizer.word_index.items():
        if index == predicted_word_index:
            return word

    return None

In [19]:
input_text="To be or not to be"
print(f"Input text:{input_text}")
max_sequence_len=model.input_shape[1]+1
next_word=predict_next_word(model, tokenizer, input_text, max_sequence_len)
print(f"Next word Prediction: {next_word}")

Input text:To be or not to be
Next word Prediction: the


- pickle.HIGHEST_PROTOCOL: This is an integer value that dynamically selects the newest, fastest, and most efficient formatting rules supported by your current version of Python.

In [20]:
import pickle
## save the tokenizer

with open('tokenizer.pickle', 'wb') as file:
    pickle.dump(tokenizer, file, protocol=pickle.HIGHEST_PROTOCOL) 

In [24]:
%load_ext tensorboard

In [27]:
%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6006 (pid 26856), started 11:28:35 ago. (Use '!kill 26856' to kill it.)

['metadata.json', 'config.json', 'model.weights.h5']
